Ilona coveralls
ilonamm/askbywho pull request #10
Opened 2017-07-10 10:21 UTC by ilonamm

2017-07-10 18:26 UTC, batmany13 requested changes
just need to change it to support circleci 2.0, and remove the circle.yml

2017-07-10 18:26 UTC, batmany13 commented on circle.yml
> +test:
we're using "circleci 2.0", so there's no longer a circle.yml file.  Take a look at .circleci/config.yml for the right place to put this stuff

2017-07-10 18:26 UTC, batmany13 commented on .coveralls.yml
> +repo_token: $coveralls_repo_token
how does this variable get set?

2017-07-10 18:26 UTC, batmany13 commented on circle.yml
> +    - mix coveralls.circle
does this work?  I tried running this locally, and it blew up

2017-07-10 18:27 UTC, ilonamm commented on .coveralls.yml
> +repo_token: $coveralls_repo_token
set it up in circleci as env variable

2017-07-11 17:17 UTC, ilonamm commented
This should work now, except for some dogma errors in code.

2017-07-11 18:26 UTC, ilonamm commented
should be all fixed, ready for @batmany13!

2017-07-12 04:40 UTC, batmany13 approved these changes

2017-07-12 04:40 UTC, merged

2017-07-12 05:23 UTC, ilonamm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set up github + circleCI + Heroku](https://trello.com/c/Dcd4hT9i/3-set-up-github-circleci-heroku)